---
- name: add earthworm.service
  template:
    src: earthworm.service.j2
    dest: /etc/systemd/system/earthworm.service
  notify: earthworm restart

- name: ensure earthworm is started
  service:
    name: earthworm
    state: started
    enabled: true
    daemon_reload: yes