---
all:
  children:
    shakealert:
      children:
        berkeley:
          hosts:
            eew-bk-int1.geo.berkeley.edu:
            eew-bk-int2.geo.berkeley.edu:
        caltech:
          hosts:
            eew-ci-int1.gps.caltech.edu:
            eew-ci-int2.gps.caltech.edu:
        menlo:
          hosts:
            eew-nc-int1.wr.usgs.gov:
            eew-nc-int2.wr.usgs.gov:
        uw:
          hosts:
            eew-uw-int1.ess.washington.edu:
            eew-uw-int2.ess.washington.edu:
        canada:
          hosts:
            eew-cn-int1.seismo.nrcan.gc.ca:
            eew-cn-int2.seismo.nrcan.gc.ca: